#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat <<'EOF'
Usage:
  install/install.sh write-project-entrypoint --agent codex|claude|kiro --profile work|personal --project-dir PATH [--force]
  install/install.sh write-codex-config [--codex-dir PATH] [--force]
  install/install.sh write-codex-project-config --project-dir PATH [--mode safe|trusted|yolo] [--force]
  install/install.sh link-agent-skills --agent codex|claude|kiro [--agent-dir PATH] [--force]
  install/install.sh link-codex-skills [--codex-dir PATH] [--force]
  install/install.sh link-claude-skills [--claude-dir PATH] [--force]
  install/install.sh link-kiro-skills [--kiro-dir PATH] [--force]

Commands:
  write-project-entrypoint  Write a thin project-local wrapper that points back to this repository's canonical steering files.
  write-codex-config        Write a baseline ~/.codex/config.toml with conservative user-level defaults.
  write-codex-project-config Write a project-local .codex/config.toml to set Codex trust and privilege for one repo.
  link-agent-skills         Symlink shared skills from this repository into a Codex, Claude, or Kiro skills directory.
  link-codex-skills         Compatibility alias for link-agent-skills --agent codex.
  link-claude-skills        Compatibility alias for link-agent-skills --agent claude.
  link-kiro-skills          Compatibility alias for link-agent-skills --agent kiro.

Options:
  --agent       Target agent for the generated entrypoint.
  --profile     Active profile to reference from the generated entrypoint.
  --project-dir Project directory where AGENTS.md or CLAUDE.md should be written.
  --mode        Codex project privilege preset: safe, trusted, or yolo.
  --agent-dir   Agent config directory. Defaults to "$HOME/.codex", "$HOME/.claude", or "$HOME/.kiro".
  --codex-dir   Codex config directory. Defaults to "$HOME/.codex".
  --claude-dir  Claude config directory. Defaults to "$HOME/.claude".
  --kiro-dir    Kiro config directory. Defaults to "$HOME/.kiro".
  --force       Replace an existing generated file or skill symlink.
EOF
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

require_dir() {
  local path="$1"
  [[ -d "$path" ]] || die "directory does not exist: $path"
}

write_file() {
  local path="$1"
  local content="$2"
  local force="$3"

  if [[ -e "$path" && "$force" != "true" ]]; then
    die "refusing to overwrite existing file: $path (use --force)"
  fi

  mkdir -p "$(dirname "$path")"
  printf '%s' "$content" >"$path"
}

write_project_entrypoint() {
  local agent=""
  local profile=""
  local project_dir=""
  local force="false"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --agent)
        agent="${2:-}"
        shift 2
        ;;
      --profile)
        profile="${2:-}"
        shift 2
        ;;
      --project-dir)
        project_dir="${2:-}"
        shift 2
        ;;
      --force)
        force="true"
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "unknown option for write-project-entrypoint: $1"
        ;;
    esac
  done

  [[ -n "$agent" ]] || die "--agent is required"
  [[ -n "$profile" ]] || die "--profile is required"
  [[ -n "$project_dir" ]] || die "--project-dir is required"
  [[ "$profile" == "work" || "$profile" == "personal" ]] || die "--profile must be work or personal"

  require_dir "$project_dir"

  local target_file=""
  local adapter_file=""

  case "$agent" in
    codex)
      target_file="$project_dir/AGENTS.md"
      adapter_file="$ROOT_DIR/adapters/codex/AGENTS.md"
      ;;
    claude)
      target_file="$project_dir/CLAUDE.md"
      adapter_file="$ROOT_DIR/adapters/claude/CLAUDE.md"
      ;;
    kiro)
      target_file="$project_dir/AGENTS.md"
      adapter_file="$ROOT_DIR/adapters/kiro/AGENTS.md"
      ;;
    *)
      die "--agent must be codex, claude, or kiro"
      ;;
  esac

  local profile_file="$ROOT_DIR/profiles/$profile/preferences.md"

  local content
  content=$(
    cat <<EOF
# Managed By agent-steering

This file was generated by:
- \`$ROOT_DIR/install/install.sh write-project-entrypoint --agent $agent --profile $profile --project-dir $project_dir\`

Canonical shared steering repository:
- \`$ROOT_DIR\`

Agent-specific adapter:
- \`$adapter_file\`

Active profile overlay:
- \`$profile_file\`

Persistent context:
- \`$ROOT_DIR/shared/context/session-memory.md\`
- \`$ROOT_DIR/shared/context/external-sources.md\`

If local needs diverge from the shared defaults, change the canonical files in the repository above instead of editing this generated wrapper by hand.
EOF
  )

  write_file "$target_file" "$content" "$force"
  printf 'wrote %s\n' "$target_file"
}

write_codex_config() {
  local codex_dir="${HOME}/.codex"
  local force="false"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --codex-dir)
        codex_dir="${2:-}"
        shift 2
        ;;
      --force)
        force="true"
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "unknown option for write-codex-config: $1"
        ;;
    esac
  done

  local target_file="$codex_dir/config.toml"
  local content
  content=$(
    cat <<'EOF'
# Managed by agent-steering install/install.sh write-codex-config
#
# Security-oriented defaults based on:
# - https://developers.openai.com/codex/security/
# - https://developers.openai.com/codex/config-basic
#
# Notes:
# - prefer keeping user-level defaults conservative and scoping stronger access to trusted projects.
# - project-local .codex/config.toml files override this file when the project is trusted.

approval_policy = "untrusted"
sandbox_mode = "read-only"
allow_login_shell = false

[sandbox_workspace_write]
network_access = false

[profiles.auto]
approval_policy = "on-request"
sandbox_mode = "workspace-write"

[profiles.readonly]
approval_policy = "untrusted"
sandbox_mode = "read-only"

[profiles.readonly_quiet]
approval_policy = "never"
sandbox_mode = "read-only"

[profiles.trusted]
approval_policy = "never"
sandbox_mode = "workspace-write"

[profiles.yolo]
approval_policy = "never"
sandbox_mode = "danger-full-access"
EOF
  )

  write_file "$target_file" "$content" "$force"
  printf 'wrote %s\n' "$target_file"
}

write_codex_project_config() {
  local project_dir=""
  local mode="trusted"
  local force="false"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --project-dir)
        project_dir="${2:-}"
        shift 2
        ;;
      --mode)
        mode="${2:-}"
        shift 2
        ;;
      --force)
        force="true"
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "unknown option for write-codex-project-config: $1"
        ;;
    esac
  done

  [[ -n "$project_dir" ]] || die "--project-dir is required"
  [[ "$mode" == "safe" || "$mode" == "trusted" || "$mode" == "yolo" ]] || die "--mode must be safe, trusted, or yolo"

  require_dir "$project_dir"

  local target_file="$project_dir/.codex/config.toml"
  local content=""

  case "$mode" in
    safe)
      content=$(
        cat <<'EOF'
# Managed by agent-steering install/install.sh write-codex-project-config
# Project-local Codex settings for a trusted repo.

approval_policy = "on-request"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = false
EOF
      )
      ;;
    trusted)
      content=$(
        cat <<'EOF'
# Managed by agent-steering install/install.sh write-codex-project-config
# Project-local Codex settings for a trusted repo.

approval_policy = "never"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = true
EOF
      )
      ;;
    yolo)
      content=$(
        cat <<'EOF'
# Managed by agent-steering install/install.sh write-codex-project-config
# Project-local Codex settings for a fully trusted repo.

approval_policy = "never"
sandbox_mode = "danger-full-access"
EOF
      )
      ;;
  esac

  write_file "$target_file" "$content" "$force"
  printf 'wrote %s\n' "$target_file"
}

link_agent_skills() {
  local agent=""
  local agent_dir=""
  local force="false"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --agent)
        agent="${2:-}"
        shift 2
        ;;
      --agent-dir)
        agent_dir="${2:-}"
        shift 2
        ;;
      --codex-dir)
        agent="codex"
        agent_dir="${2:-}"
        shift 2
        ;;
      --claude-dir)
        agent="claude"
        agent_dir="${2:-}"
        shift 2
        ;;
      --kiro-dir)
        agent="kiro"
        agent_dir="${2:-}"
        shift 2
        ;;
      --force)
        force="true"
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "unknown option for link-agent-skills: $1"
        ;;
    esac
  done

  [[ -n "$agent" ]] || die "--agent is required"

  case "$agent" in
    codex)
      agent_dir="${agent_dir:-${HOME}/.codex}"
      ;;
    claude)
      agent_dir="${agent_dir:-${HOME}/.claude}"
      ;;
    kiro)
      agent_dir="${agent_dir:-${HOME}/.kiro}"
      ;;
    *)
      die "--agent must be codex, claude, or kiro"
      ;;
  esac

  mkdir -p "$agent_dir/skills"

  local skill_dir
  for skill_dir in "$ROOT_DIR"/shared/skills/*; do
    [[ -d "$skill_dir" ]] || continue

    local skill_name
    skill_name="$(basename "$skill_dir")"
    local target="$agent_dir/skills/$skill_name"

    if [[ -L "$target" || -e "$target" ]]; then
      if [[ "$force" != "true" ]]; then
        die "refusing to overwrite existing ${agent} skill path: $target (use --force)"
      fi
      rm -rf "$target"
    fi

    ln -s "$skill_dir" "$target"
    printf 'linked %s -> %s\n' "$target" "$skill_dir"
  done
}

link_codex_skills() {
  link_agent_skills --agent codex "$@"
}

link_claude_skills() {
  link_agent_skills --agent claude "$@"
}

link_kiro_skills() {
  link_agent_skills --agent kiro "$@"
}

main() {
  local command="${1:-}"
  [[ -n "$command" ]] || {
    usage
    exit 1
  }
  shift || true

  case "$command" in
    write-project-entrypoint)
      write_project_entrypoint "$@"
      ;;
    write-codex-config)
      write_codex_config "$@"
      ;;
    write-codex-project-config)
      write_codex_project_config "$@"
      ;;
    link-agent-skills)
      link_agent_skills "$@"
      ;;
    link-codex-skills)
      link_codex_skills "$@"
      ;;
    link-claude-skills)
      link_claude_skills "$@"
      ;;
    link-kiro-skills)
      link_kiro_skills "$@"
      ;;
    -h|--help)
      usage
      ;;
    *)
      die "unknown command: $command"
      ;;
  esac
}

main "$@"
